Restaurant.create(name: "Nandos", address: "Commercial St 27", category: "belgian")
Restaurant.create(name: "Jamie's Italian", address: "Liverpool St 123", category: "italian")
Restaurant.create(name: "Le Gorumand", address: "Paris", category: "french")
Restaurant.create(name: "Chopstix", address: "Scumbag Lane 81", category: "chinese")
Restaurant.create(name: "Itsu", address: "Spitalfields Market", category: "japanese")
Restaurant.create(name: "The Real Belgian", address: "Unwanted Street 58", category: "belgian")
